class LockState
  attr_reader elements: Array[Integer]

  def initialize: (Array[Integer] elements) -> void

  def distance_to: (LockState other) -> Integer

  def neighbours: () -> Array[LockState]

  def ==: (LockState other) -> bool
  
  def eql?: (LockState other) -> bool
  
  def hash: () -> Integer

  private

  def neighbours_by_index: (Integer index) -> Array[LockState]
end
